### ISSUE TITLE
Pod will not be deleted if it has been paused

### ISSUE THREAD

**Issue by SkYNewZ** [knative-sandbox/container-freezer#44]
I am testing this feature and it seems to do exactly what it is supposed to do: pause containers that are no longer receiving requests.

However, still with Knative, when my service receives no more traffic, the pods are submitted for deletion by the scheduler. But in my case, the pods being paused, they remain in `Terminating` state indefinitely: the `queue-proxy` already takes several minutes between the "Shutdown complete, exiting..." log message and the actual shutdown of the container (about 15 minutes in most cases). Then, the `user-container` never stops (I tried with a custom image and with [`traefik/whoami`](https://hub.docker.com/r/traefik/whoami)).

I think it is impossible to delete a container/pod paused by containerd (and Docker too for that matter) but I would like to have your confirmation.

So how do you get the (paused) pod to actually be destroyed when Knative requests it? Moreover, since the pod is terminating, if the traffic goes back up, new pods will be created, so new pods will be terminating indefinitely, etc.

Here is the manifest for the service:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
  namespace: default
spec:
  template:
    metadata:
      name: hello-world
    spec:
      containers:
        - image: traefik/whoami
          ports:
            - containerPort: 80

```
